
### Recuperar todos los productos
GET http://localhost:1234/products



### Recuperar un producto por id
GET http://localhost:1234/products/2

### Recuperar los productos por tipo
GET http://localhost:1234/products?tipo=pileta


### Crear un producto

POST http://localhost:1234/products
Content-Type: application/json

{
  "nombre": "Envase",
  "descripcion": "Envase de plástico",
  "tipo": "otros",
  "imagen": "https://envaseplastico.jpg",
  "precio": 1800
}


### Modificar algo de un producto

PATCH http://localhost:1234/products/2
Content-Type: application/json

{
  "precio": 3250
}

### Borrar un producto

DELETE http://localhost:1234/products/14